### ISSUE TITLE
pods installation issue in react native ios

### ISSUE THREAD

**Issue by asadumair** [DolbyIO/comms-sdk-react-native#116]
[!] CocoaPods could not find compatible versions for pod "VoxeetSDK":
  In Podfile:
    react-native-comms-sdk (from `../comms-sdk-react-native-latest`) was resolved to 3.8.0-beta.1, which depends on
      VoxeetSDK (~> 3.8.0)

Specs satisfying the `VoxeetSDK (~> 3.8.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by mohsindlb** [comment]
@asadumair 3.8.0-beta.1 has just now released, can you please check again?

**Comment by asadumair** [comment]
> @asadumair 3.8.0-beta.1 has just now released, can you please check again?

there is pods issue in that

**Comment by asadumair** [comment]
> @asadumair please run `pod repo update` in ios directory of your app.

this is working thanks
