### ISSUE TITLE
Object is not a function error when trying to call any UnsubscribeFunction

### ISSUE THREAD

**Issue by dannyBies** [DolbyIO/comms-sdk-react-native#128]
I'm trying to integrate this SDK but am running into an issue when trying to unsubscribe from an event handler.
When I navigate to one of my screens I can successfully view the incoming video. However when going to the previous screen I get an error when calling the `UnsubscribeFunction`. This results in the event handler functions not being disposed which means if you keep going back and forth between screens you will have multiple event handlers active while there should only be one. 

I can consistenly reproduce this with the following code, you don't need to have called any other Dolby function:
``` 
useEffect(() => {
    logger.debug("~~~~~~~~ subscribing to onStreamsChange");
    const unsubscribe = CommsAPI.conference.onStreamsChange((data, type) => {
      logger.debug("~~~~~~~~ onStreamsChange", type);
    });

    return () => {
      logger.debug("~~~~~~~~ unsubscribing from onStreamsChange");
      try {
        unsubscribe();
        logger.debug("~~~~~~~~ unsubscribing from onStreamsChange");
      } catch (e) {
        logger.error("~~~~~~~~ error unsubscribing", e);
      }
    };
  }, []);
```
Note: it happens for any `onX` handler, not just `onStreamsChange`

Logs after toggling between screens a few times:
![image](https://user-images.githubusercontent.com/3967506/232532721-106f6d67-2558-4955-bdfe-1ff0b8240dec.png)

Full logs for completeness sake:
![image](https://user-images.githubusercontent.com/3967506/232529950-2d273d85-90de-4db1-95e7-af0ec4c47f4d.png)

**Comment by graduad** [comment]
Thank you very much for reporting this issue. We will be looking into it as soon as possible.

**Comment by kbetl-dlb** [comment]
Fixed: https://github.com/DolbyIO/comms-sdk-react-native/pull/130

**Comment by dannyBies** [comment]
That'd be great!

**Comment by graduad** [comment]
Should be fixed in https://www.npmjs.com/package/@dolbyio/comms-sdk-react-native/v/3.8.1-beta.1 .

**Comment by dannyBies** [comment]
I just tested it and it works great now, thanks!
