### ISSUE TITLE
Unable to view network requests in the debugger.

### ISSUE THREAD

**Issue by dannyBies** [DolbyIO/comms-sdk-react-native#129]
Network requests do not show up in [flipper](https://fbflipper.com/) which makes it difficult to debug issues. I believe this is due to this SDK calling the android/ios specific SDKs to make network requests. 

Is there any way to view these requests and responses without going into android/ios specific tooling?

**Comment by graduad** [comment]
Network request are indeed crated by the Android and iOS SDKs, hence observing network requests in ReactNative will not log them in Flipper. Perhaps using the Flipper SDK/plugins in the native projects may help, but I have not tried it and do not know if it will actually work.

But I was wondering, is there a particular issue you have troubles with?
