### ISSUE TITLE
Incorrect values in ParticipantType enum

### ISSUE THREAD

**Issue by dannyBies** [DolbyIO/comms-sdk-react-native#133]
The values in the ParticipantType enum seem to be incorrect.
When I log `(await CommsAPI.conference.current()).participants` whilst in a conference. I get back the following data:
![image](https://user-images.githubusercontent.com/3967506/233106511-b6dfc8a7-9cac-4f71-9157-51151e4d68ae.png)

The enum indicates it is "user" while it should be "USER". I have not verified this but I think this might be the case for some of the other enums as well.
https://github.com/DolbyIO/comms-sdk-react-native/blob/33d6e72b573fa05d2fbfa5a35925835c8be1a804/src/services/conference/models.ts#L216-L220

It's also possible to receive the type "UNKNOWN" which should be added to the enum.
![image](https://user-images.githubusercontent.com/3967506/233107096-00080ceb-80d3-48ff-9b70-3a67f7e30718.png)

**Comment by graduad** [comment]
Should be fixed in 3.8.1-beta.2 which is released now.
