### ISSUE TITLE
Unable to import any enum type

### ISSUE THREAD

**Issue by dannyBies** [DolbyIO/comms-sdk-react-native#134]
When trying to import any enum you get the following error:
![image](https://user-images.githubusercontent.com/3967506/233107636-b785b67d-d7c5-470c-b732-004cd7d60157.png)

This happens for every enum defined in a `.d.ts` file that you try to import.

**Comment by FabienLavocat** [comment]
Could you try something like:
```js
if (participant.status === ('CONNECTED' as ParticipantStatus)) {

}
```

**Comment by dannyBies** [comment]
That would work but you'd loose type-safety that way, as this would be valid.
```
if (participant.type !== ("NONEXISTENTVALUE" as ParticipantStatus)) {
}
```

Just for the record, this isn't a big issue for us as we can use the string literal.
```
if (participant.status === 'CONNECTED') {
}
```

The issue is that it conflicts with one of our eslint-rules that we have configured https://typescript-eslint.io/rules/no-unsafe-enum-comparison/ . 

It also removes some of the type-safety that would normally come with using an enum in our linting setup
![image](https://user-images.githubusercontent.com/3967506/233310698-dda877c5-d17a-412d-8220-47fe22fa64db.png)

**Comment by graduad** [comment]
We are working on this, and we hope to provide a solution in a coming beta version.
