### ISSUE TITLE
CommsAPI.session.isOpen returns the wrong type

### ISSUE THREAD

**Issue by dannyBies** [DolbyIO/comms-sdk-react-native#137]
`isOpen` returns a `Boolean` instead of a `boolean`, the primitive type should always be returned as otherwise you need to call `valueOf` to unwrap the actual value. This was probably a typo as this seems to be the only instance where `Boolean` is used instead of `boolean`.

Current code:
```
const isOpen = await CommsAPI.session.isOpen();
if (isOpen.valueOf()) {}
```

Expected code:
```
const isOpen = await CommsAPI.session.isOpen();
if (isOpen) {}
```

https://github.com/DolbyIO/comms-sdk-react-native/blob/33d6e72b573fa05d2fbfa5a35925835c8be1a804/src/services/session/SessionService.ts#L33-L35

**Comment by graduad** [comment]
Thank you very much for your comment. Unfortunately `isOpen` has been part of our public API for some time now, and changing its return type may be incompatible with existing codebases. We will be looking at a remedy for this, in one of the next major releases.

**Comment by graduad** [comment]
@FabienLavocat , mentioned that it may be acceptable to incorporate such a small change of the public API in 3.9. @srynk what do you think?

**Comment by kbetl-dlb** [comment]
Fixed in this PR: https://github.com/DolbyIO/comms-sdk-react-native/pull/202
