### ISSUE TITLE
Stream Removed is not received when someone leaves a conference

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#155]
We see that the Participant Status changes to LEFT but no Stream Removed event is received.

**Comment by kbetl-dlb** [comment]
This happen on android device only, cannot reproduce on Ios device. Problem is releaded with Android native SDK, during test I checked that react native  not getting stream removed events from sdk when participant left, only participant left event appear on react native.

**Comment by rkanu-dolby** [comment]
I confirm that this issue is in SDK itself. 
Fix is on its way.

**Comment by graduad** [comment]
As per internal communication fixes in the native SDKs should be delivered in 3.10. 

Hence testing in React Native is needed.

**Comment by mpozy** [comment]
Tested. Works properly.
