### ISSUE TITLE
Stopping video can trigger different events

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#156]
Stopping video sometimes causes us to get Stream Removed, but other times we seem to just get Participant Updated.

**Comment by graduad** [comment]
Additionally, multiple Participant Updated events are received around the same time, with same data.

**Comment by FabienLavocat** [comment]
The stream removed event will be triggered when both video and audio are not sent to the platform, if the audio is on but the participant turns off the camera, then the stream updated event will be triggered, not stream removed. @dannyBies is this the behavior you are experiencing?

**Comment by dannyBies** [comment]
We do get EVENT_CONFERENCE_STREAM_UPDATED when we turn of the video but our audio is still on, this is expected.

However, sometimes we do not get EVENT_CONFERENCE_STREAM_REMOVED when our audio is off and we then turn our video off. 
It looks like toggling the audio on and then off results in the removed event not firing. If we do not change the audio state we do get the removed event coming through.

A couple of conferences where we reproduced this issue:

ID: 34a13da7-215b-4bb5-80e9-3c59ea81f725
Alias: Stage|91f898eb-d79f-4987-9002-0fcb4f48001c|d3f81d71-d859-4ef1-bb58-c0d41fbaf6d1

ID: 535121aa-5959-438a-bb8a-f2fe5c8b69eb
Alias: Stage|91f898eb-d79f-4987-9002-0fcb4f48001c|d5941e03-ccbc-449b-af28-5955626ba7de

**Comment by FabienLavocat** [comment]
Thank you for providing the two conference IDs, this is super useful. From what I see in the logs, you are not stopping the audio. There is a difference between a `mute` operation and `stop audio`. The mute will keep the audio connection sent to the platform, but obviously the audio from the microphone is not sent (we send empty frames) but if you stop the audio then we actually stop the connection to the server.
So, in those two conferences, I think it makes sense that the `EVENT_CONFERENCE_STREAM_REMOVED` is not triggered.

**Comment by graduad** [comment]
@FabienLavocat , given you findings, shall we close this ticket?
