### ISSUE TITLE
Multiple stream events received when changing camera

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#157]
It has been noticed that when a participant is sharing video from their camera, but then changes to a different video device, several events are being received, with one of the intermediate events containing no video streams. This means that there is a short gap between the old and new video streams.

**Comment by mkrzy-dolby** [comment]
What platform? iOS/Android or both?

**Comment by codlab** [comment]
if it's the web which is changing the camera device, it's most likely that the implementation is doing a stopVideo then startVideo. In such event, StreamUpdated will be fired to warn that no camera is received and then a new stream event containing the video stream will be received.

**Comment by FabienLavocat** [comment]
Like @codlab is saying, this is related to the Web SDK behavior of changing camera, this has been fixed in the [Web SDK 3.10.0 beta.1](https://github.com/voxeet/voxeet-sdk-web/releases/tag/3.10.0-beta.1). I will close this ticket for now.
cc: @dannyBies

**Comment by dannyBies** [comment]
I've just confirmed that this works great now, thanks!
