### ISSUE TITLE
Implement UI for testing 2 simultaneous screen shares (if needed)

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#175]
If the test app does not contain the ability to show 2 simultaneous screen shares, this needs to be implemented.

Please investigate how it is possible to test two concurrent screen shares.

**Comment by kbetl-dlb** [comment]
two similtaneous screen share will be available for android in 3.11 sdk version

**Comment by graduad** [comment]
No new UI is needed, but there are issues with 2 screen shares as per  https://github.com/DolbyIO/comms-sdk-react-native/issues/208
