### ISSUE TITLE
screenshare in android is not working

### ISSUE THREAD

**Issue by asadumair** [DolbyIO/comms-sdk-react-native#50]
CommsAPI.conference.startScreenShare(t)
            .then(() => {
                alert('success')
            }).catch((e) => {
                alert('error')
            });

**Comment by kdrob-dolby** [comment]
Your android activity needs to inherit from `CommsAPISDKAppCompatActivity`.
Please let me know if this fixes your issue.

**Comment by asadumair** [comment]
> Your android activity needs to inherit from `CommsAPISDKAppCompatActivity`. Please let me know if this fixes your issue.

can you please elaborate with implementation so we can check??

**Comment by mohsindlb** [comment]
@asadumair please look at the example [here](https://github.com/DolbyIO/comms-sdk-react-native/blob/develop/example/android/app/src/main/java/com/example/reactnativedolbyiosdk/MainActivity.java)


`import io.dolby.sdk.comms.reactnative.android.activities.CommsAPISDKAppCompatActivity;

public class MainActivity extends CommsAPISDKAppCompatActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "CommsSDKExample";
  }
}`

**Comment by asadumair** [comment]
we should write our customized code.
we are not getting this solution how we can implement this

**Comment by nadeembutt** [comment]
> @asadumair please look at the example [here](https://github.com/DolbyIO/comms-sdk-react-native/blob/develop/example/android/app/src/main/java/com/example/reactnativedolbyiosdk/MainActivity.java)
> 
> `import io.dolby.sdk.comms.reactnative.android.activities.CommsAPISDKAppCompatActivity;
> 
> public class MainActivity extends CommsAPISDKAppCompatActivity {
> 
> /**
> 
> * Returns the name of the main component registered from JavaScript. This is used to schedule
> * rendering of the component.
>   */
>   @OverRide
>   protected String getMainComponentName() {
>   return "CommsSDKExample";
>   }
>   }`

It worked. Thanks for your help.
