### ISSUE TITLE
Update to 3.8 native SDKs

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#69]
Update the Dolby.io React Native SDK to use the 3.8 native SDKs.

Tasks:

- [ ] Update the Android part of Dolby.io React Native SDK
- [ ] Update the iOS part of Dolby.io React Native SDK

**Comment by graduad** [comment]
Update to Android SDK 3.8.2.

**Comment by dannyBies** [comment]
Hi!

I was wondering if there is an estimate for adding support for the 3.9.0 SDK?

Due to https://github.com/DolbyIO/comms-sdk-react-native/issues/61 I am unable to release my app without being able to connect to a conference using real-time-streaming.

**Comment by graduad** [comment]
We are currently planning the 3.9.0 SDK release, but we have not finalised the date yet.
