### ISSUE TITLE
Add the conference events to the notification service RN+Android

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#74]
Add following events to the notification service:
- conference crated
- conference ended

Only RN and Android work. iOS to be done in separate ticket.

**Comment by mohsindlb** [comment]
Can you please add activeParticipant, participantLeft and participantJoined event also? This is helpful if any Listener joined or left the conference this event will help to manage participant list, similar to native sdk events.

**Comment by graduad** [comment]
Implemented in 3.8.0 Beta 1
