### ISSUE TITLE
Add the activeParticipats event to the notification service RN+Android

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-react-native#76]
Add following events to the notification service:
- active participants

Only RN and Android work. iOS to be done in separate ticket.

**Comment by mohsindlb** [comment]
Please add following events also

- participantJoined
- participantLeft

**Comment by graduad** [comment]
@mohsindlb, we have planed this already under a different ticket. Please see: https://github.com/DolbyIO/comms-sdk-react-native/issues/75

**Comment by graduad** [comment]
Implemented in 3.8.0 Beta 1

@asadumair iOS is implemented as well, but as per first message, it has been tracked in a different ticket.
