### ISSUE TITLE
When we add a new listener how we can check or know the new user is came?? so please tell me the way because these two type of notifications are not available in react native if these are available then we can identify using these notifications

### ISSUE THREAD

**Issue by asadumair** [DolbyIO/comms-sdk-react-native#94]
please read it carefully for react native read it carefully then go for closed and support

**Comment by graduad** [comment]
This ticket seems to be very similar to https://github.com/DolbyIO/comms-sdk-react-native/issues/87. As mentioned in it the work for this kind of functionality was already scheduled in https://github.com/DolbyIO/comms-sdk-react-native/issues/75 and https://github.com/DolbyIO/comms-sdk-react-native/issues/82. **Both are now deployed in version 3.8.0 Beta 1 and hence I am closing this.** (Please see: https://docs.dolby.io/communications-apis/docs/rn-client-sdk-references-notificationservice)

Should I have misunderstood your request, or find that the events from the notification service are not working correctly please raise a new ticket.
